lsi: false
safe: true
source: https://github.com/UnderCover0tter/undercover0tter.github.io.git
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
